[package]
name = "breez_sdk_spark_flutter"
version = "0.1.3"
edition = "2024"

[workspace]

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
async-trait = "0.1.88"
# Replaced with release commit during publishing
breez-sdk-common = { git = "https://github.com/breez/spark-sdk.git", rev = "bdeb1745f6cea01f6e186fa176000b47ea4515c7" }
breez-sdk-spark = { git = "https://github.com/breez/spark-sdk.git", rev = "bdeb1745f6cea01f6e186fa176000b47ea4515c7", features = ["openssl-vendored"] }
extend = "1.2.0"
flutter_rust_bridge = "=2.9.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
