[package]
name = "breez-sdk-spark-flutter"
version = "0.1.3"
edition = "2024"

[workspace]

[lib]
name = "breez_sdk_spark_flutter"
crate-type = ["cdylib", "staticlib"]

[dependencies]
async-trait = "0.1.88"
# Replaced with release commit during publishing
breez-sdk-common = { git = "https://github.com/breez/spark-sdk.git", rev = "28ef3498d0dbd936cb0b58ce0cb23b3ff7c3a8ac" }
breez-sdk-spark = { git = "https://github.com/breez/spark-sdk.git", rev = "28ef3498d0dbd936cb0b58ce0cb23b3ff7c3a8ac", features = ["openssl-vendored"] }
extend = "1.2.0"
flutter_rust_bridge = "=2.11.1"

[build-dependencies]
flutter_rust_bridge_codegen = "=2.11.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
