[package]
name = "breez-sdk-spark-flutter"
version = "0.1.3"
edition = "2024"

[workspace]

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
async-trait = "0.1.88"
# Replaced with release commit during publishing
breez-sdk-common = { git = "https://github.com/breez/spark-sdk.git", rev = "06594f40e291d6e08135d81d76f7b7135a7fb461" }
breez-sdk-spark = { git = "https://github.com/breez/spark-sdk.git", rev = "06594f40e291d6e08135d81d76f7b7135a7fb461" }
extend = "1.2.0"
flutter_rust_bridge = "=2.11.1"

[build-dependencies]
flutter_rust_bridge_codegen = "=2.11.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
